### ISSUE TITLE
Not handling long _MemberData properly

### ISSUE THREAD

**Issue by DougHennig** [fdbozzo/foxbin2prg#16]
SQConfigEngine in SQConfig.vcx in the attached zip file has 7945 characters in _MemberData. The XML in _MemberData has no carriage return (CHR(13)) or linefeed (CHR(10)) characters. When I convert it to a VC2 file and then back to a VCX file and edit the class, I get a "Property '_memberdata' value is too long" error message if I select the _MemberData property in the Properties window and then click on the Class or right-click and choose Zoom. The reason is because the XML is now 8071 characters. The extra length is caused by linefeed characters at the end of each tag.

FoxBin2PRG should not insert CHR(10) if it was not in the original text (actually, in the specific case of _MemberData, you can leave out CHR(13), CHR(10), and CHR(9) since they are not required).

[Test.zip](https://github.com/fdbozzo/foxbin2prg/files/1604640/Test.zip)

**Comment by fdbozzo** [comment]
Hi Doug! It's fixed in v1.19.49.6

Please, confirm it's working for you too.

Best Regards.-

**Comment by DougHennig** [comment]
I still see linefeed characters in _MemberData. I looked at the updated code in FoxBin2PRG.prg and didn't see a change that would impact this.

**Comment by fdbozzo** [comment]
Hi Doug! you are right, I forgot to push the changes!

You can see them now.

**Comment by DougHennig** [comment]
Yes, it works now. Thanks for the fast response on this and the other issue!
